### ISSUE TITLE
Tracking issue: Pgwire Client(Frontend) API

### ISSUE THREAD

**Issue by sunng87** [sunng87/pgwire#221]
As we already have a solid backend API, I'm starting to build a client API with similar granularity with our current backend API. Hopefully with this API we will be able to build the proxy framework on top of pgwire.

Tasks:

- Tokio
  - [ ] Tokio client message codec
  - [ ] Tokio client
  - [ ] TLS client
  - [ ] connection management, reconnect
- API
  - [ ] startup api
    - [ ] authentication mechanisms
      - [ ] cleartext
      - [ ] to be added
  - [ ] request-response style apis
    - [ ] simple query
    - [ ] extended query
  - [ ] callback style apis
    - [ ] notification

**Comment by Lilit0x** [comment]
Hi @sunng87, is this on the priority list, orare  there other issues or features that are needed before this? What of #80?

**Comment by sunng87** [comment]
I see. The replication protocols are completely independent features that doesn't blocked anything from current pgwire applications. Implementing it may add more use-cases for pgwire related to data replication. 

Another topic we would like to invest is providing a higher level API for cancellation, that can be used in [datafusion-postgres](https://github.com/datafusion-contrib/datafusion-postgres/). It requires some level of session management. I hope it can be optional and generic enough.
